flowchart LR
    subgraph "Event Sources"
        C[CouchDBWatchers]
        W[FileSystemWatchers]
    end
    
    subgraph "Event Handlers"
        F[FlowcellHandler]
        B[BestPractiseHandler]
        D[DeliveryHandler]
    end

    subgraph "Realms"
        R[FlowcellRealm]
        A[BestPractiseRealm]
        P[DeliveryRealm]
    end
    
    Core[YggdrasilCore]
    
    C & W --> Core
    Core --> B & F & D
    F e1@==> R
    B e2@==> A
    D e3@==> P
    e1@{ animate: true }
    e2@{ animate: true }
    e3@{ animate: true }