
sequenceDiagram
    participant FSWatcher as FileSystemWatcher
    participant ProjectsDBSource
    participant YggdrasilDBSource
    participant YggCore as YggdrasilCore
    participant RealmMgr as Realm
    
    ProjectsDBSource->>ProjectsDBSource: Monitors DB changes
    FSWatcher->>FSWatcher: File is created
    note left of FSWatcher: Watchdog triggers on_created
    
    FSWatcher->>YggCore: emit(YggdrasilEvent)
    YggCore->>YggCore: handle_event(event)
    alt event matches "flowcell_ready"
        YggCore->>RealmMgr: load realm logic
        activate RealmMgr
        RealmMgr->>RealmMgr: validate data, run pipeline
        RealmMgr->>YggCore: success/failure status
        deactivate RealmMgr
    else event not recognized
        YggCore->>YggCore: log warning
    end

    note left of ProjectsDBSource: Change occured
    ProjectsDBSource->>YggCore: emit_event(YggdrasilEvent)
    YggCore->>YggCore: handle_event()
    alt event matches "BP analysis"
        YggCore->>RealmMgr: load realm logic
        activate RealmMgr
        RealmMgr->>RealmMgr: validate data, run pipeline
        RealmMgr->>YggCore: success/failure status
        deactivate RealmMgr
    else event not recognized
        YggCore->>YggCore: log warning
    end
    
    note left of YggdrasilDBSource: Change occured
    YggdrasilDBSource->>YggCore: emit_event(YggdrasilEvent)
    YggCore->>YggCore: handle_event()
    alt event matches "Delivery"
        YggCore->>RealmMgr: load realm logic
        activate RealmMgr
        RealmMgr->>RealmMgr: validate data, run pipeline
        RealmMgr->>YggCore: success/failure status
        deactivate RealmMgr
    else event not recognized
        YggCore->>YggCore: log warning
    end

    